CMSSNU/SKFlatAnalyzer

setup_tmp.sh

For now, we have to use home directories in KISTI,
becuase any files with "**creation** time > 3 month ago" will be removed under scratch (new KISTI policy).
Please move your working directories, and update with this PR, if you work in KISTI.
I will merge this into master branch tomorrow.

update setup_tmp for kisti. now use home directory not scratch

---

data/Run2Legacy_v1/2017/ID/Electron/histmap.txt
data/v949cand2_2/2017/ID/Electron/histmap.txt

correct typo in 2017 electron ID histmap

correct typo in 2017 electron ID histmap

---

Analyzers/include/AnalyzerCore.h
Analyzers/include/MCCorrection.h
Analyzers/src/AnalyzerCore.C
Analyzers/src/MCCorrection.C

Some updates on PUReweight
1. MCCorrection::GetPileUpWeight**As**SampleName -> MCCorrection::GetPileUpWeight**By**SampleName
2. Create a general PU reweighting function in AnalyzerCore (AnalyzerCore::GetPileUpWeight) which treats DataYear automatically

update on PU reweight

---

Analyzers/src/SKFlatNtuple.C
python/CheckJobStatus.py

I experienced 'hadd' start before WriteHist() finished, which result in incomplete output file.
This can be a problem when there are so many histograms that WriteHist() takes long time.
This is because "JOB FINISHED" is printed just after event loops end.
So, I changed few lines.

modifying finish point to prevent from hadding before WriteHist

---

python/SKFlat.py

I think it will be good to have an option for test run with only some fraction of total events.
SKFlat.py --reduction 100 .... will run with about 1/100 of total events.
I tested it by ExampleRun with DYJets.

add an option for test run with only some part of events

---

python/SKFlat.py

Skimming improved
Before, "-n" option was not allowed for making a skimmed tree (but still, skimming only works at tamsa1 or 2).
Now, we can use this option for skimming jobs.
1. Original ntuples are saved in `/data7/DATA/SKFlat/`, and skimmed ntuples are sent to `/data8/DATA/SKFlat/`. This is to reduce the workload on the I/O.
1. The output path is `/data8/DATA/SKFlat/<SKFlat Tag>/<Year>/MC_SkimTree_<SkimName>/<Sample Name (DAS name)>/<TimeStamp of Skimming job>/`
E.g., `/data8/DATA/SKFlat/Run2Legacy_v1/2016/MC_SkimTree_LRSMHighPt/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/2019_03_26_025209/`

Improve skimming; allow -n option

---

AnalyzerTools/include/MCCorrection.h
AnalyzerTools/src/MCCorrection.C
Analyzers/include/AnalyzerCore.h
Analyzers/src/AnalyzerCore.C
python/SKFlat.py
setup_tmp.sh

ROOT always attaches the new object s(e.g., histogram obtained with Get() functions) to the currently opened file. If the file is closed, then the object memory is set free.
Before, TFile opened in MCCorrection::ReadHistograms() were not closed due to this reason.
Since CATAnalyzer, to prevent this, we created a new TDirectory and clone the histograms here,
and close the TFile safely.
I use this in our MCCorrection class.

MCCorrection TFiles closed properly

---

python/CheckJobStatus.py
python/SKFlat.py

When using Condor, we compress all the libraries, data files, and run files, and then send it to the sandbox.
This was done because scratch had some issues in KISTI, so nodes sometimes could not access scratch directories.
However, it looks like this is fixed, and also we use home directory in KISTI.
Condor in TAMSA also can access working directories, so I found no reason to make tar files.
This made the job submission very slow (espcially in TAMSA).
Now this is fixed, and submission is enhanced a lot.

condor submission faster

---

Analyzers/include/GetEffLumi.h
Analyzers/src/GetEffLumi.C

Faster GetEffLumi using SetBranchStatus function
I didn't compare the speed, but I think this way will be much faster than current version.
And with SetBranchStatus, I think we can make faster SkimTree. I will test it when server is free.
I tested it with 2016 DYJets sample, and it gave me same sumW with SampleCommonInfo.

Faster GetEffLumi

---

Analyzers/src/SkimTree_LRSMHighPt.C
python/SKFlat.py

1.  Faster skimming code using SetBranchStatus (Analyzers/src/SkimTree_LRSMHighPt.C)
- read full entries only for trigger passing events
- I expect small effect since there is still heavy writing. But anyway, it will faster than before.
2. Using only one node for skimming (python/SKFlat.py)
- due to slow IO of SNU servers... this way would provide more stable environment for other users. And total running time will be similar, I think.
3. adding for failure (python/SKFlat.py L335)
- I found that sometimes SKFlat.py cannot know its failure when there is no SF hist.
When we call Lepton SF function, it check histmap. And if SF hist doesn't exist, root script exit with EXIT_FAILURE code, but without any stderr. (only stdout saying there is no histogram)
So, we need to leave something at …

update skimming to use only one node. And faster skimming code

---

Analyzers/src/AnalyzerCore.C
DataFormats/include/Electron.h
DataFormats/include/Muon.h
DataFormats/src/Electron.C
DataFormats/src/Muon.C

- for RoccoR v3
Muon::TrackerLayers() 
Muon::SetTrackerLayers(int n)
- for SMP analysis. I used long name in order to follow the convention. 
Electron::IsGsfCtfScPixChargeConsistent(); 
Electron::SetIsGsfCtfScPixChargeConsistent(bool b);
Tested with modified ExampleRun

Add TrackerLayers to Muon class; Add IsGsfCtfScPixChargeConsistent to Electron class;

---

Analyzers/include/AnalyzerCore.h
Analyzers/src/AnalyzerCore.C

1. Update AnalyzerCore for TH3
1. TH1 SetDirectory(0) for speed
-- I think there is some issue TDirectory when there are too many object. Destructor of an object is very slow (10000obj /10min) when there are more than O(100000) objects in same TDirectory (probably due to L3 cache missing).
-- We register all of the TH in the c++ map, and delete them at the end. So, we can simply SetDirectory(NULL) to solve the problem. This results in very fast deleting (~sec).

Update AnalyzerCore for TH3; TH1 SetDirectory(0) for speed

---

Analyzers/src/AnalyzerCore.C
Analyzers/src/ExampleRun.C
Analyzers/src/SKFlatValidation.C

JSFillHist is a function which takes a form of
JSFillHist(Directory name, histogram name, ~~), and it uses 
`std::map< TString, std::map<TString, TH1D*> > JSmaphist_TH1D`
which is a map of a map.
@jalmond reported that it becomes very slow when we have many histograms.
Thanks to @sansan9401 , FillHist can do the exact same thing, and has more features : 
`FillHist("dirA/dirB/dirC/histname", ~)`
I now recommend the users use FillHist, and avoid JSFillHist.
For now I keep this function, but I will remove them in the future.
I replaced JSFillHist from example and SKFlatValidation codes in this commit.
AnalyzerCore::FillLeptonPlots and AnalyzerCore::FillJetPlots are also modified.

replace JSFillHist to FillHist

---

AnalyzerTools/src/MCCorrection.C
DataFormats/include/Electron.h
DataFormats/src/Electron.C

HEEP ID for 2018 endcap electron (EE) has been updated : https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaRunIIRecommendations#HEEPv7_0_2018Prompt
We have to modify two cuts; 1) H/E 2) EM+Had_depth1 isolation
Out of the 12 cut variables of HEEP ID, we "H/E" has bit number "6" and "EM+Had_depth1 isolation" has bit number 8 : https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Applying_Individual_Cuts_of_a_Se
If an electron pass original HEEP ID, the ID cut bit is 2^12-1 = 4095.
If we remove above two cuts, the ID cut bit is (4095) - (2^6) - (2^8) = 3775.
So, the new ID will be requiring below three cuts :
- ( (ID cut bit) & 3775 ) = 3775
- New H/E cut
- New EM+Had_depth1 isolation cut
This is implemented as Electron::passHEEP2018Prompt() function. Objects under …

Update/hee pv7.0 2018 prompt

---

README.md

This is an updated in the submodule GEScaleSyst.
https://github.com/jedori0228/GEScaleSyst/commit/06dbb793af0d6f3850fd9ee10ae4793227dfa5b0
In external/GEScaleSyst/, `int verbose` was not initialized.
I found when I'm unlucky, it is set to `1` and printing all the logs.
This is now fixed by initializing in the constructor.

GEScaleSyst: verbose was not initilized.

---

Analyzers/include/AnalyzerCore.h
Analyzers/src/AnalyzerCore.C

Update of genmatching code used by SNU students.
Major changes:
1) FinalPhotonSt23 in the CatAnalyzer code is recovered here.
In case of external conversion, checking this kinds of photons should not be ignored. In principle, final state photon should be status-1, but I put this function in the CatAnalyzer code as I observed there are many of such cases. I believe this is due to skimming generator history between pythia and MiniAOD. I put a link to explicit example of this case in this shared link: https://cernbox.cern.ch/index.php/s/yQwJxnWMp7S9Tji
2) external conversion matching condition reoptimized.
Previous dR and dPtRel cuts are optimized for electron with PT>25. Now the cuts are reoptimized for PT>10. dR cut is sill valid for PT[10-25] but dPtRel cut is changed from 0.2 to 0.5
3) …

v200821 - update shared gen-matching code

---

AnalyzerTools/src/BTagCalibrationStandalone.C

Related to #110 
There are *pow(x,1.5)* functions in [the csv file for 2016 DeepJet Tight](https://github.com/CMSSNU/SKFlatAnalyzer/blob/e2952427a5b789e79a49ea9e8a820d8b45799983/data/Run2UltraLegacy_v2/2016preVFP/BTag/wp_deepJet_106XUL16preVFP_v2.csv#L16). We need to distinguish this comma here from the csv delimiter (also comma) when read the csv files.

fixbug for 2016 DeepJet Tight

---

python/SKFlat.py

* @youngwan-kim reports that he cannot access some files in gv0. I believe this is a bug during *remove-brick* procedure of the glusterfs. 
* I found that it is fixed when executing `ls` on its mother directory. So, I added some lines to do `ls` before read files.

for gluster bug during remove-brick

---

python/SKFlat.py

Reverts CMSSNU/SKFlatAnalyzer#114
@jbhyun reports that this solution (#114) is not work for long jobs as the files disappear again after some time.
The problem is that gluster looks up a file over sub-volumes with the hash table using the file name. It is usually fine, but the hash table may be not correct during removing its sub-volume. As you know, I removing and adding sub-volumes for the transition from RAID5 to RAID6.
Now, I turned off one of the gluster option (*cluster.lookup-optimize*) so that gluster searches all the sub-volumes. This resolved the issue and this commit is not needed anymore.

Revert "for gluster bug during remove-brick"

---

AnalyzerTools/src/MCCorrection.C

1. pt range up to 200 GeV for isomu triggers
2. findbin should be in eta,pt order now for all 3 years
3. if there is no muon in the event, force 1.0

bug fixes for MuonTrigger_SF

---

setup.sh

* ROOT 6.22.08 has a bug in `hadd`. See https://github.com/root-project/root/issues/9939
* CMSSW_11_3_0 (ROOT 6.22.08) -> CMSSW_11_2_5 (ROOT 6.22.06)
* You need to do `make distclean` after merging

fixbug: ROOT 6.22.08 -> 6.22.06 due to very slow hadd

---

python/PrintOldLogs.py
python/UserInfo_template.py
setup.sh

checks log directory and removes logs that are too old automatically
safety trigger set to 3days as some jobs might be submitted 12.29 night and still runs in 12.30 or 12.31.
if it's set to -1 , it won't remove anything automatically

add automatic log removal function

---

setup.sh

Tested histogram yields in ExampleRun (by @Chihwan-An)
—————————————————————
histogram : ZCand_Mass_POGMedium_Central 
—————————————————————-
tamsa2 : 
slc7_amd64_gcc900/CMSSW_11_2_5 ->  824926.96
gamsa : 
el9_amd64_gcc11 / CMSSW_13_0_10 -> 824926.96
el9_amd64_gcc12 /CMSSW_15_0_1    -> 824926.96
—————————————————————
histogram : ZCand_Mass_POGTight_Central 
—————————————————————-
tamsa2 : 
slc7_amd64_gcc900/CMSSW_11_2_5 ->  800739.04
gamsa : 
el9_amd64_gcc11 / CMSSW_13_0_10 -> 800739.04
el9_amd64_gcc12 /CMSSW_15_0_1    -> 800739.04

Use root in CMSSW_15_0_1, default for NanoV15
